# config.sh -- autogenerated Sat Feb 11 16:18:58 CET 2017

CFBundleDisplayName=jsonedit
CFBundleName=jsonedit
CFBundleIdentifier=org.epichrome.app.jsonedit
SSBVersion=2.1.16
SSBUpdateCheckDate=1487431137
SSBUpdateCheckVersion=2.1.16
SSBProfilePath=Library/Application\ Support/Epichrome/Apps/jsonedit
SSBChromePath=/Applications/Google\ Chrome.app
SSBChromeVersion=56.0.2924.87
SSBRegisterBrowser=No
SSBCustomIcon=Yes
SSBFirstRunSinceVersion=''
SSBHostInstallError=''
SSBCommandLine=( --app=https://vintagexav.github.io/JSONedit/ )
